version: "3"

services:
  frontend:
    image: hbpmip/mip-ebrains-eu:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    links:
      - backend

  backend:
    image: strapi/strapi
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 1337:1337
    volumes:
      - ./backend:/srv/app
    depends_on:
      - db
    command: bash -c "yarn install && yarn build && yarn start"

  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./db/prod/${POSTGRES_DB}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
