version: "3"

services:
  frontend:
    container_name: mipfrontend
    image: hbpmip/mip-ebrains-eu:latest
    ports:
      - 8080:80

  backend:
    container_name: mipbackend
    image: strapi/strapi
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 1337:1337
    volumes:
      - ./backend:/srv/app
    depends_on:
      - db
    command: strapi start

  db:
    container_name: mipdb
    image: postgres
    restart: always
    volumes:
      - ./db/prod/${POSTGRES_DB}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
