version: "3"

services:
  devfrontend:
    container_name: devfrontend
    image: node
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: yarn serve

  devbackend:
    container_name: devbackend
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=devdb
      - DATABASE_PORT=5432
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 1337:1337
    volumes:
      - ./backend:/srv/app
    depends_on:
      - devdb

  devdb:
    container_name: devdb
    image: postgres
    restart: always
    volumes:
      - ./db/dev/${POSTGRES_DB}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
